[pytest]
filterwarnings =
    ignore::DeprecationWarning:fastapi.*
    ignore::DeprecationWarning:websockets.*
    ignore::DeprecationWarning:pydantic.*
    ignore::DeprecationWarning:main
    ignore:Using .httpx. with .starlette.testclient. is deprecated
